### ISSUE TITLE
It doesn't work unless adding a backslash

### ISSUE THREAD

**Issue by Rux77** [RonMelkhior/tailwindcss-dir#1]
Thank you for this plugin,

I am testing it with the latest version of tailwindcss ( v1.0.0-beta.4 )

After playing with it, it doesn't work unless adding a backslash ( \ ) before the **separator**:
return `[dir="${dir}"] .${dir}\\${separator}${className}`;

**Comment by RonMelkhior** [comment]
Thanks for letting me know, I'll take a look in the next day or two and get
back to you.

**Comment by RonMelkhior** [comment]
Fixed in `tailwindcss-dir@next`, I'll publish it under the latest tag once Tailwind 1.0 is stable.

**Comment by RonMelkhior** [comment]
Published under `latest` now that 1.0 is out.
