### ISSUE TITLE
Error: Couldn’t find Tailwind screen: ltr

### ISSUE THREAD

**Issue by sanishkr** [RonMelkhior/tailwindcss-dir#10]
`npm install tailwindcss-dir --save-dev
`

in tailwind.config.js - added
```
variants: {
         padding: ['responsive', 'direction'],
},
plugins: [
	require('tailwindcss-dir')(),
],
```

And added `ltr:px-4 rtl:px-2 ` in some component

**Comment by RonMelkhior** [comment]
Hi!

Could you please tell me what you tried to do that led you to this error?

**Comment by RonMelkhior** [comment]
@sanishkr 

That should work. Where does it note that error?

**Comment by RonMelkhior** [comment]
If you use `babel-plugin-tailwind-components`, that's probably the issue. It seems like it has pretty limited support for custom variants.

**Comment by sanishkr** [comment]
Yeah, I was using babel loader. Anyway, thanks @RonMelkhior. I found another approach to solve my issue.
