### ISSUE TITLE
rtl: and ltr: doesn't work

### ISSUE THREAD

**Issue by 3adeling** [RonMelkhior/tailwindcss-dir#13]
Hi..

I installed tailwind in my project (laravel) using [tailwind-preset](https://github.com/laravel-frontend-presets/tailwindcss)
and then installed tailwindcss-dir following the installation steps.
but both `ltr:` and `rtl:` is not working 

my `tailwind.config.js`:
```
module.exports = {
  theme: {
    extend: {}
  },
  variants: {
    float: ['responsive', 'direction'],
    margin: ['responsive', 'direction'],
    padding: ['responsive', 'direction'],
    textAlign: ['responsive', 'direction'],
  },
  plugins: [
    require('tailwindcss-dir')(),
  ]
}
```

**Comment by RonMelkhior** [comment]
Hi, sorry for the late reply. Do you still have this issue?

**Comment by amidesfahani** [comment]
is it possible to use this plugin in NOVA?

**Comment by RonMelkhior** [comment]
If Nova allows you to change your classes, sure.

**Comment by 3adeling** [comment]
hey @RonMelkhior, yea I still have the issue

I am using it with https://github.com/laravel-frontend-presets/tailwindcss

maybe something is missing in the installation steps?

**Comment by 3adeling** [comment]
I found the solution. I have to run `npm run dev` or `npm run watch` after adding the plugin to tailwind config
