### ISSUE TITLE
Use `margin-inline` instead

### ISSUE THREAD

**Issue by Yiddishe-Kop** [RonMelkhior/tailwindcss-dir#15]
First of all - Thank you! Great project!

For margin, padding, borders etc:

I think it would be better to use `margin-inline-start` & `margin-inline-end` [same for padding etc.] instead of adding dir variants.

The advantage of this approach:
1. Write less code: write only one class that will handle both directions.
2. Smaller bundle size: no need to generate all the variants...

**Comment by RonMelkhior** [comment]
Yup I considered it, but it leads to worse browser support. The project I wrote this package for needed to support older browsers.
