### ISSUE TITLE
Use dir with :last and :first variants

### ISSUE THREAD

**Issue by pedrofsantoscom** [RonMelkhior/tailwindcss-dir#18]
Hello,

Is there a way to use `dir` variants with `last` or `first` variants? 
I've tried various way and can't make it work. Any ideas?
```
works:
- last:mr-0
- lg:last:mr-0

doesn't work:
- rtl:last:mr-0
- lg:rtl:last:mr-0
```

tailwind.config.js
```js
...
variants: {
   margin: ({ after }) => after(['direction', 'last', 'first']),
}
```

**Comment by AMAFsoft** [comment]
Any one ?

**Comment by RonMelkhior** [comment]
Chaining variants is supported, but you'd have to check the order it puts the variants in the compiled CSS file.
