### ISSUE TITLE
How can I set border to rtl and ltr direction ?

### ISSUE THREAD

**Issue by ghost** [RonMelkhior/tailwindcss-dir#21]
How can I set Border to rtl and ltr direction ?
for example: 
`<input   class="w-5/6 sm:w-11/12 border-b-0 border-t-0 ltr:border-l-0 rtl:border-r-0 p-3 ltr:float-left rtl:float-right rounded-none"  type="search" name="search" id="search" >`

In the above code `ltr:border-l-0 rtl:border-r-0` does not work.

**Comment by RonMelkhior** [comment]
Are you sure you added the variant properly?

**Comment by ghost** [comment]
yes, padding, margin, and float working good. but border doesn't work even with `border: ['responsive', 'direction'],`

**Comment by RonMelkhior** [comment]
There isn't a `border` class.

These are the default options:

```
borderCollapse: ['responsive'],
    borderColor: ['responsive', 'dark', 'group-hover', 'hover', 'focus'],
    borderOpacity: ['responsive', 'group-hover', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
```

Try to add the variant to `borderWidth`

**Comment by ghost** [comment]
Yes. now working well. Thank you. 👍
