### ISSUE TITLE
it is not work :(

### ISSUE THREAD

**Issue by eng-faris** [RonMelkhior/tailwindcss-dir#25]
I try <div class="text-green text-2xl ltr:pl-4 rtl:pr-4">
not work I do all steps :(

**Comment by eng-faris** [comment]
ltr:pl-4

**Comment by RonMelkhior** [comment]
That is not nearly enough info for me to go on. What's your Tailwind config, for starters?

**Comment by eng-faris** [comment]
module.exports = {
  purge: [
    './resources/**/*.blade.php',
    './resources/**/*.js',
    './resources/**/*.vue',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {
    float: ['responsive', 'direction'],
    margin: ['responsive', 'direction'],
    padding: ['responsive', 'direction'],
    },
  },
  plugins: [
    require('tailwindcss-dir')(),
  ],
}

**Comment by eng-faris** [comment]
new one install not use any plugin

**Comment by eng-faris** [comment]
frist : i forget thank you for your reply :)

**Comment by eng-faris** [comment]
I use Laravel 8 and just install Tailwind and use your plugin thank you

**Comment by eng-faris** [comment]
it is work rtl and ltr but not this   ltr:pl-4 rtl:pr-4

**Comment by eng-faris** [comment]
it is work I don't how but work thank you :)
