### ISSUE TITLE
Support right and left ?

### ISSUE THREAD

**Issue by jeanali** [RonMelkhior/tailwindcss-dir#26]
Hi, I have a simple style:

LTE
<img width="254" alt="Screen Shot 2021-04-09 at 3 22 14 PM" src="https://user-images.githubusercontent.com/67483209/114179420-a0891c00-9947-11eb-84a6-7afebb2067cb.png">

RTL
<img width="277" alt="Screen Shot 2021-04-09 at 3 23 33 PM" src="https://user-images.githubusercontent.com/67483209/114179550-d0382400-9947-11eb-98a5-bf6043ecb524.png">

With this code:

```
<span class="absolute inset-y-0 lte:left-0 rtl:right-0 w-1 bg-indigo-600 rounded" aria-hidden="true"></span>
```

It is worked with ``lte`` but ``rtl`` the right arrow does not work!

**Comment by RonMelkhior** [comment]
There's no `lte` variant. Only `ltr` and `rtl`

If it doesn't work, make sure you added the 'direction' variant to the rules you need. By default the README's example config only adds those variants for float, margin and padding.

**Comment by jeanali** [comment]
@RonMelkhior  Sorry for the typo, I added the right and left in variant:

```
variants: {
        right: ['responsive', 'direction'],
        left: ['responsive', 'direction'],
        float: ['responsive', 'direction'],
        margin: ['responsive', 'direction'],
        padding: ['responsive', 'direction'],
    },
```

**Comment by RonMelkhior** [comment]
Instead of right & left in the config, do `inset: ['responsive', 'direction'],`. Should work then

**Comment by jeanali** [comment]
THANKS 👍
