### ISSUE TITLE
Windicss Typography plugin and tailwindcss-dir

### ISSUE THREAD

**Issue by AldeonMoriak** [RonMelkhior/tailwindcss-dir#28]
Hello, is it possible to use this plugin in Windicss and its Typography plugin?
I want to have RTL  support for `prose` class.

**Comment by RonMelkhior** [comment]
`prose` seems to only change the font size, so I don't see any reason for it to not work. If it doesn't let me know.

**Comment by AldeonMoriak** [comment]
Would you be so kind to take a look at [this](https://github.com/AldeonMoriak/windi-dir-test)?

**Comment by AldeonMoriak** [comment]
RTL support has been added to windicss typography  plugin.
[This issue](https://github.com/windicss/windicss/issues/286)
