### ISSUE TITLE
I couldn't use it

### ISSUE THREAD

**Issue by hakhsin** [RonMelkhior/tailwindcss-dir#6]
Hi, I flow document. But it don't work yet. I am using Vue and tailwind within laravel. I added this to `tailwind.config.js`:
```
plugins: [
    require('tailwindcss-dir')(),
],
    modules: {
	float: ['responsive', 'direction'],
	margin: ['responsive', 'direction'],
	padding: ['responsive', 'direction'], 
},
```
But when I added the `rtl:pr-4' in my element it dose not work. What should I do?

**Comment by hakhsin** [comment]
Thank you I found how use it.

**Comment by RonMelkhior** [comment]
Glad you figured it out!

Out of curiosity, what was the issue?

**Comment by hakhsin** [comment]
Hi, I didn't understand this section of document:
> Finally, you can use the plugin and add it to modules you want to use it with.
```
modules: {
	float: ['responsive', 'direction'],
	margin: ['responsive', 'direction'],
	padding: ['responsive', 'direction'],
},
```
So, I added exactly it in `tailwind.config.js`. But I remember suddenly tailwind document and understood what I have to do.
Thank you for this plugin.
